### ISSUE TITLE
Installation of breastPhantom

### ISSUE THREAD

**Issue by lyup666** [DIDSR/VICTRE#10]
Hello Team VICTRE,

Thank you for developing this great software and for making it open source. 
In your documentation, you give the instruction to install this software on the Ubuntu 16.04 system. But I am using Centos 7 system, could you give me some advice to intall breastPhantom based on Centos 7.
Thank you very much.

Best wishes,
Li Yang

**Comment by diksha-s** [comment]
Hello,
We would like to recommend using Ubuntu since it is the tested OS for VICTRE.  Unfortunately, we cannot provide support for other OS.
