### ISSUE TITLE
Air kerma simulation

### ISSUE THREAD

**Issue by katrien-houbr** [DIDSR/VICTRE#15]
Hello,

I'm interested in how the number of histories is determined. Therefore I tried to replicate the air kerma method described in the MCGPU section. However, I'm not able to obtain the reported simulated source exposure of 3.7e-9 µGy/history for the 30kVp W/Rh spectrum.

Briefly described I've made a 10x10x10 voxel model (voxelsize 0.2mm) with 0 (=air) allocated to each voxel. I also changed the source position to 1m. With my simulation parameters, that can be found in attachment, I obtain a simulated source exposure of 5.7e-9 µGy/history. Do you any idea what I'm doing wrong? I've made no changes in the MCGPU code.

Thank you very much,
Katrien

[output_projection.txt](https://github.com/DIDSR/VICTRE/files/7668162/output_projection.txt)

**Comment by andreubs** [comment]
Hi Katrien,

The reason your conversion factor is different than ours is that you used the field aperture for dense and hetero breasts (15.0  7.4686667 deg), while the conversion factor reported in the paper was for scattered breasts that used the full-field aperture (15.0 11.203 deg). The smaller aperture is 2/3 the size of the larger one (to avoid wasting time simulating x-rays outside the smaller breasts). If you multiply your estimated factor by 2/3 you get very close to our value. 

Two other differences in our simulation: we disabled the source motion blur and simulated a 1-mm-thick compression paddle in the voxelized geometry, above the ionization chamber. The paddle was included in the experimental setting, as mentioned in section 3.1 (p. 16) in the National Health System Cancer Screening Program equipment report 1306 [28].

I am attaching the files I used to get the exposure value for the paper (you will see an energy deposited in air [mat 15] of 23.00664 eV/hist -> 3.69e-9 microGy/hist).

[MC-GPU_v1.5b_exposure_conversion_factor_30kVp_Aperture15.0x11.203.in.txt](https://github.com/DIDSR/VICTRE/files/7671650/MC-GPU_v1.5b_exposure_conversion_factor_30kVp_Aperture15.0x11.203.in.txt)
[MC-GPU_v1.5b_exposure_conversion_factor_30kVp_Aperture15.0x11.203_2e12hist.out.txt](https://github.com/DIDSR/VICTRE/files/7671651/MC-GPU_v1.5b_exposure_conversion_factor_30kVp_Aperture15.0x11.203_2e12hist.out.txt)
[paddle_air_chamber_5x5x100.vox.txt](https://github.com/DIDSR/VICTRE/files/7671652/paddle_air_chamber_5x5x100.vox.txt)

Best regards,

    Andreu
