### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by brunodesanti** [DIDSR/VICTRE#16]
Dear authors, 
first of all thanks for the precious work.

I would like to ask you help because I am having a problem when installing the breastPhantom on my UBUNTU 16.04 machine.

I am able to build all the libraries (libduct.a, libcreateArtery.a etc..) but Im encountering an error in linking CXX executable breastPhantom. 

I attach a screenshot.

![image](https://user-images.githubusercontent.com/91621685/158814181-5aeeb71b-4cc6-4ddc-85b5-9bac38ed5e4c.png)

Thank you for the assistance.

Best regards,
Bruno De Santi

**Comment by malago86** [comment]
Hi Bruno,

It looks like there is a conflict with another folder named `breastPhantom`, can you double check that inside the folder with the cxx files there is no folder named `breastPhantom`?

Alternatively, you can also try with the automatic pipeline, it has a script that will compile everything directly and link all the modules in a single Python class: https://github.com/DIDSR/VICTRE_PIPELINE

Also, take a look at this example on Google Colab, it might help you set up your environment: https://colab.research.google.com/drive/1g8bwH_nuVRn3xJcoqP-zT7bz8kY4Nuqz?usp=sharing

Let us know if you still have issues!
