### ISSUE TITLE
Question about ROI coordinates

### ISSUE THREAD

**Issue by DragonDuck** [DIDSR/VICTRE#18]
Hello!

I have a few (related) questions about the ROI coordinates for the dataset. I'm afraid I may be missing a critical bit of information and would be very grateful for your help. I'm having some issues reconciling the ROI data from the Github repo (https://github.com/DIDSR/VICTRE_DM_ROIs) and the dataset provided on [The Cancer Imaging Archive](https://wiki.cancerimagingarchive.net/display/Public/The+VICTRE+Trial%3A+Open-Source%2C+In-Silico+Clinical+Trial+For+Evaluating+Digital+Breast+Tomosynthesis#3987920053ea3637ff1442f6bba608c13cc0e869). Specifically, my goal is to obtain the voxel coordinates of signal-positive ROIs.

1. The ROIs saved in the VICTRE_DM_ROI repo are split between "signal-absent" and "signal-present" ROIs. However, the "signal-present" ROIs only have pixel coordinates for the mammograms but not voxel coordinates for the reconstructed volumes. Is there a way to locate the ROIs in the DBT volumes themselves?
2. Related to that, I'm a bit confused about the the "signal-absent" ROIs. The `readme.txt` files state that the ROIs are given in voxel coordinates, but shouldn't that mean the Z-coordinate shouldn't be greater than the number of slices generated by the reconstruction? I'm seeing far larger Z-values, e.g. the file `roi_SA_2000680575.loc` has the coordinates:

```
300 1346 159 184 1272
985 1291 498 622 1301
409 1177 646 261 1371
634 1184 178 390 1371
360 729 312 224 1653
1029 1160 451 647 1384
663 1163 492 418 1381
754 907 599 480 1544
568 1417 203 350 1227
898 1187 577 571 1365
471 1262 204 290 1323
378 1611 277 234 1105
```

In addition, the x- and y- coordinates (first two columns?) appear to be greater than the actual dimensions of the corresponding volume slices.

I feel like I'm missing a critical detail. How can I obtain the locations of masses and calcifications in the reconstructed DBT volumes?

Thank you so much for your help!

**Comment by diksha-s** [comment]
Hello,

1. You can find the voxel locations for signal-present ROIs as well as DBT locations under Locations folder (https://github.com/DIDSR/VICTRE/tree/master/Locations).
2. Remember these are mammogram signal absent ROI locations file, the first three are corresponding voxel locations from phantom, and last two are corresponding locations in the mammogram (with fixed dimensions 3000x1500). There is no reconstruction here. 

Hope this helps!

**Comment by DragonDuck** [comment]
I see, thank you very much! One quick follow-up question, if I may, is there a meaning to some of the IDs in the filenames being negative, e.g.

```
roi_SP_-2036005888.loc
roi_SP_282746787.loc
```

I thought they might differentiate virtual patients with and without lesions, but they don't seem to correlate with the numbers presented in the paper (https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2717000) and I can't tell from the data itself what the difference is, if any.

**Comment by diksha-s** [comment]
No. Random numbers corresponding to phantoms can be negative or positive and is unrelated to any patient anatomy.
