### ISSUE TITLE
How to extract individual tissue components as a 3D model

### ISSUE THREAD

**Issue by rasunag27** [DIDSR/VICTRE#5]
Dear team VICTRE,

Thank you for providing this excellent open source code of Breast Phantom. I have been working on the breast Phantom and could execute with required parameters smoothly.

1. I would like to extract individual parameters from the Phantom. i.e. How can I extract only "Duct" from the Phantom?  Or any other components.
2. How can I scale down the model so that the tissue components can be integrated into another model.?

Thanks and Regards,

Sunag R A.

**Comment by andreubs** [comment]
Hi Sunag,

Happy to see that you were able to run the code. I will try to answer your questions.

   1. Do you mean that you want to have a voxelized phantom with only one tissue in it? This should be easy to do with a post-processing script that reads the voxel values in a regular phantom and outputs 0 for every material number that you don't want. You could also edit the code where the phantom is written to disk at the end of file breastPhantom.cxx to output only the tissue you like.  

    2. You can choose the size of the output phantom voxels with the input parameter "imgRes=". You could also generate a very high resolution phantom and then use a post-processing script to downscale to the size you want.

Have a nice day.

      Andreu

**Comment by rasunag27** [comment]
Dear Andreu,

      Thank you very much for your reply. Based on your reply, I tried to implement changes in breastPhantom.cxx but I could not able the preferred result or I could get the same outputs. I actually wanted to get the output of each individual tissue in .vti format. When I run the code, the default outputs we get are combined breastPhantom vti and separately with arteryFill and veinFill vti extensions. 

So, I tried to make changes in breastPhantom.cxx to get output of each individual tissue say as cooper, nipple, duct etc.

Based on the understanding of VICTRE document, I would like to extract the duct something like the one provided in the image link below which is extracted from document.

[duct file](https://drive.google.com/file/d/1hRf9gJd-OoUSzqHMIEn0hj35vnWtqp5O/view?usp=sharing)
 
Could you please help me out with the changes of code in breastPhantom.cxx.? I think I have lost track in understanding the code of .cxx file. 

Thanks and Regards,

Sunag R A.

**Comment by andreubs** [comment]
Modifying the breastPhantom.cxx code is always hard. I would recommend generating a standard phantom, opening it with paraview, python, matlab or imagej, and setting to 0 all the voxels that do not have the tissue number that you want.

**Comment by rasunag27** [comment]
Dear Andreu,

1. Thank you very much for your reply. I actually modified the tissueStruct in BreastPhantom and could obtain the Phantoms for particular tissues. But, I am unable to obtain for only milk-ducts. I have attached the images of the obtainted Phantoms.

[Standard_Phantom](https://drive.google.com/file/d/1S5CrBq8QTvv3VLsFhe55kAEFuSQUMPFR/view?usp=sharing)

[Without_muscle](https://drive.google.com/file/d/1_aDutDntajdn6GqHDUUFo0_bSTFNofki/view?usp=sharing)

[Without_muscle_nipple](https://drive.google.com/file/d/1M-vtKvJLvVjWSNgpJq-ABYuemX3C2eoS/view?usp=sharing)


Below I have the image where I modify and got the above volumetric view. In this if I make make 0 by keeping only duct, I get error. So, I am unable to get duct alone.

[Image_tissue_struct](https://drive.google.com/file/d/1SqKcVvUb3Fxw77fwiQBoUDxs-owZgA7N/view?usp=sharing)


2. Apart from this, I ran the breastPhantom without any cfg file addressed. I obtainted the ideal spherical Breastphantom. This result is very good for my research. But once it rans, I found the cfg file empty from the result. How to obtain the cfg file of the ideal Breast Phantom.? I have put the image of the ideal BreastPhantom below.

[Ideal_Breast_Phantom](https://drive.google.com/file/d/1GFfhUh7DPT8W2NGDFX-_za1C9nuXjuEN/view?usp=sharing)

Thanks and Regards,

Sunag R A.
