### ISSUE TITLE
Question about DM projection dataset

### ISSUE THREAD

**Issue by kimnamu** [DIDSR/VICTRE#6]
Hi Thanks for sharing a good dataset and pipeline codes

I am inquiring because there is confusion in viewing the data.
It is different from the DM projection image introduced by the article and the DM projection image uploaded on VICTRE.
Changing brightness and contrast makes it difficult to obtain similar images.

How do I get an article image from the VICTRE data?

1. VICTRE image
<img width="300" alt="Screen Shot 2020-12-17 at 10 20 16 AM" src="https://user-images.githubusercontent.com/41357160/102425834-771f4a00-4051-11eb-9881-438fe29decf6.png">

2. Article image
<img width="300" alt="Screen Shot 2020-12-17 at 10 20 42 AM" src="https://user-images.githubusercontent.com/41357160/102425851-856d6600-4051-11eb-9e08-60804da7b16b.png">

**Comment by diksha-s** [comment]
Hello, the article images were enhanced for display purposes and the lesions were made more conspicuous by increasing their radiography attenuation during imaging.  For the VICTRE image, you can use ImageJ for viewing the breast phantom internal anatomical structures to some extent.  Select an area within the breast and then use Image -> Adjust -> Brightness or Window level.  Hope this helps!

**Comment by kimnamu** [comment]
Thank you for replying

**Comment by kimnamu** [comment]
Hi @diksha-s 
I have one more question.
Can you see why the VICTRE image looks like black and white inverted?

**Comment by diksha-s** [comment]
You can invert the LUT in ImageJ for viewing.
