### ISSUE TITLE
Can I use customized phantom?

### ISSUE THREAD

**Issue by kimnamu** [DIDSR/VICTRE#7]
Hi, I try to test using the VICTRE tool.
Can I use a customized phantom? For example, a rectangular cube.
In other words, how do I make a customized .raw.gz file?

**Comment by diksha-s** [comment]
Hello, you cannot generate a rectangular phantom with our breast generation tools.  You can try using the VICTRE Imaging tools for your customized phantom after making the appropriate changes to the input files.

**Comment by kimnamu** [comment]
I got it. Thank you for replying
