### ISSUE TITLE
Images generated from different phantoms look very similar

### ISSUE THREAD

**Issue by NicoleHD215** [DIDSR/VICTRE#9]
Hello. I have been using the VICTRE pipeline (specifically breastPhantom, breastCompress, breastCrop and x-ray imaging) and recently noticed that two images (mammography) that I got from different phantoms that I generated, with different fat percentage, look very similar.

I took the following steps:

1. I used breastPhantom to generate a handful of phantoms with different fat percentage. I used the file 'breastPhantom/cfg/VICTRE_dense.cfg' and only changed line 25, target fat.
2. I used breasCompress and breastCrop normally.
3. I generated .in files for the x-ray imaging part of the pipeline. Here, I edited the file 'VICTRE_MCGPU/example_simulations/MC-GPU_v1.5b_hetero_phantom_mammo_fast.in', specifically lines:
 -22, I changed the number of stories to the original number 1.7e11
 -39, output image filename
 -68, 69, 70 and 75 to match the cropped phantoms size
 -73, voxel geometry file
4. I used the modified files and the instructions in 'VICTRE_MCGPU/example_simulations/readme.md' to generate simulated mammography images.

Now, I am looking at a couple of the files using ImageJ and they look very similar. When I modify the brightness I see differences on the internal structures of the images, but why do the shape of the breast looks the same? I am interested in generating a small synthetic dataset of images and I would like to be able to generate various shapes and sizes of breast, how can I do so?

I attach the image with the shape that I am getting repeatedly (no brightness modification)

![Screenshot_2021-04-16 ImageJ JS(2)](https://user-images.githubusercontent.com/72849293/114985001-e9fdcd80-9e57-11eb-8f58-63136977eff1.png)

 along with some of the images with the brightness modified where I do see they are from different phantoms

![Screenshot_2021-04-16 ImageJ JS(1)](https://user-images.githubusercontent.com/72849293/114985016-ef5b1800-9e57-11eb-8121-c7d434a042fb.png)
![Screenshot_2021-04-16 ImageJ JS](https://user-images.githubusercontent.com/72849293/114985103-0863c900-9e58-11eb-9301-5c6125a1d3d7.png)

Thanks in advance for any help!

**Comment by diksha-s** [comment]
Hello,
In VICTRE, we used four breast density categories (dense, heterogeneously dense, scattered and fatty), and each category has its specific (fixed) breast shape and size.  Thus changing target fat fraction within the same .cfg file will render same breast shapes/sizes but with varying fat fraction.  This is what you are seeing.  I would suggest using a different .cfg file (for instance, VICTRE_fatty.cfg) if you want to see changes in shape/size, but do remember that some other breast parameters will also change between these two configuration files.  Hope this helps.

**Comment by NicoleHD215** [comment]
Thank you very much, I will check the differences between the files, beyond the target fat fraction, and see how I can get different breast shapes.
